model:
  provider: google         # or "hf" for HuggingFace
  model_name: gemini-1.5-pro
  # api_key: your_google_api_key
  # service_account_json: /path/to/service_account.json

task:
  type: doc_retrieval   #mlm
  domain: technology
  num_records: 2

output:
  save_intermediate_results: True
  folder: output
  format: jsonl
